
# violent crimes ----------------------------------------------------------

violent_crimes <- c(
  'AGGRAVATED SEXUAL ASBUSE',
  'ASSAULT 2,1,UNCLASSIFIED',
  'ASSAULT 3 & RELATED OFFENSES',
  'ASSAULT 3',
  'ASSAULT OTHER PUBLIC SERVICE EMPLOYEE',
  'ASSAULT POLICE/PEACE OFFICER',
  'ASSAULT SCHOOL SAFETY AGENT',
  'ASSAULT TRAFFIC AGENT',
  'FELONY ASSAULT',
  'FELONY SEX CRIMES',
  'HOMICIDE-NEGLIGENT,UNCLASSIFIE',
  'HOMICIDE-NEGLIGENT-VEHICLE',
  'KIDNAPPING & RELATED OFFENSES',
  'HOMICIDE, NEGLIGENT, VEHICLE,',
  'HOMICIDE,NEGLIGENT,UNCLASSIFIE',
  'KIDNAPPING',
  'KIDNAPPING 1',
  'KIDNAPPING 2',
  'MURDER & NON-NEGL. MANSLAUGHTER',
  'ROBBERY',
  'RAPE',
  'RAPE 1',
  'RAPE 1,ATTEMPT',
  'RAPE 2',
  'RAPE 3',
  'ROBBERY, CHAIN STORE',
  'ROBBERY, PAYROLL',
  'ROBBERY,ATM LOCATION',
  'ROBBERY,BANK',
  'ROBBERY,BAR/RESTAURANT',
  'ROBBERY,BEGIN AS SHOPLIFTING',
  'ROBBERY,BICYCLE',
  'ROBBERY,BODEGA/CONVENIENCE STORE',
  'ROBBERY,CAR JACKING',
  'ROBBERY,CHECK CASHING BUSINESS',
  'ROBBERY,CLOTHING',
  'ROBBERY,COMMERCIAL UNCLASSIFIED',
  'ROBBERY,DELIVERY PERSON',
  'ROBBERY,DWELLING',
  'ROBBERY,GAS STATION',
  'ROBBERY,HOME INVASION',
  'ROBBERY,LICENSED FOR HIRE VEHICLE',
  'ROBBERY,LICENSED MEDALLION CAB',
  'ROBBERY,NECKCHAIN/JEWELRY',
  'ROBBERY,ON BUS/ OR BUS DRIVER',
  'ROBBERY,OPEN AREA UNCLASSIFIED',
  'ROBBERY,PERSONAL ELECTRONIC DEVICE',
  'ROBBERY,PHARMACY',
  'ROBBERY,POCKETBOOK/CARRIED BAG',
  'ROBBERY,PUBLIC PLACE INSIDE',
  'ROBBERY,RESIDENTIAL COMMON AREA',
  'ROBBERY,UNLICENSED FOR HIRE VEHICLE',
  'SEXUAL ABUSE',
  'SEXUAL ABUSE 3,2',
  'SEX CRIMES',
  'STRANGULATION 1ST')

# property crimes ---------------------------------------------------------




































